#!/bin/bash

workFolder=$(readlink -f $(dirname $0))
path=`echo $workFolder | awk -F"/" ' { print $(NF) } '`

cp -a config_sample/*.config.php configuration/
cp -a config_sample/*.ini.php configuration/
cp -a config_sample/*.ini configuration/

cat > configuration/db.config.ini.php << EOF
[noname]
gg=fake_data
gt=just the time to generate a good one
EOF

cat > configuration/db.config.php << EOF
<?php
 if (! defined('DB_DEFAULT'))
 {
     define("DB_DEFAULT", "pmacontrol");
 }
EOF

cat >  configuration/webroot.config.php << EOF
<?php

/*
 * if you use a direrct DNS set : define('WWW_ROOT', "/");
 * if you dev in local or other use : define('WWW_ROOT', "/path_to_the_final_directory/");
 * example : http://127.0.0.1/directory/myapplication/ => define('WWW_ROOT', "/directory/myapplication/");
 * Don't forget the final "/"
 */


if (! defined('WWW_ROOT'))
{
    define('WWW_ROOT', "/$path/");
}
EOF

chmod 777 -R tmp/

## disable support for transparent hugepages in Linux for TokuDB
#redhat
if test -f /sys/kernel/mm/redhat_transparent_hugepage/enabled; then
	echo never > /sys/kernel/mm/redhat_transparent_hugepage/enabled
fi

#centos & debian
if test -f /sys/kernel/mm/transparent_hugepage/enabled; then
   echo never > /sys/kernel/mm/transparent_hugepage/enabled
fi
if test -f /sys/kernel/mm/transparent_hugepage/defrag; then
   echo never > /sys/kernel/mm/transparent_hugepage/defrag
fi

#check composer && composer install

if test -f ./vendor/glial/glial/Glial/Bootstrap.php; then
   echo "Glial Installed !"
else
    composer -V foo >/dev/null 2>&1 || { echo >&2 "PmaControl require composer but it's not installed.  Aborting."; echo "To install composer : ";echo ""; echo "        curl -sS https://getcomposer.org/installer | php";  echo "        \$ mv composer.phar /usr/local/bin/composer"; echo ""; exit 1;}

    composer install
fi


php application/webroot/index.php install index

php application/webroot/index.php install createOrganisation

php application/webroot/index.php install createAdmin

php application/webroot/index.php agent updateServerList


# install crontab
#*      *       *       *       *       cd /data/www/pmacontrol && ./glial dot generateCache


# set du daemon SELECT * FROM `daemon_main` (choisir les valeus en fonction de la machine) 